version: '3.8'

services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

  backend:
    container_name: backend
    build: registry.gitlab.com/teivys04/meta-plate/backend
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    depends_on:
      - redis
  frontend:
    container_name: frontend
    build: registry.gitlab.com/teivys04/meta-plate/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

